let Player_1 = sprites.create(assets.image`TESTCHARACTER1`, SpriteKind.Player)
let Player_2 = sprites.create(assets.image`TESTCHARACTER2`, SpriteKind.Player)
controller.player1.moveSprite(Player_1, 100, 75)
controller.player2.moveSprite(Player_2, 100, 75)
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(Player_1)
